# Generated by Django 5.1.3 on 2024-11-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office_staff',
        ),
    ]
