# Generated by Django 5.1.3 on 2025-02-16 06:55

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_order_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_filter', models.IntegerField(default=True)),
                ('s_gst', models.FloatField(default=0, null=True)),
                ('c_gst', models.FloatField(default=0, null=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('discount_amount', models.FloatField(default=0, null=True)),
                ('cash_amount', models.FloatField(default=0, null=True)),
                ('phone_pe_amount', models.FloatField(default=0, null=True)),
                ('pos_machine_amount', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='', max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(unique=True)),
                ('pin', models.IntegerField()),
                ('hotel_address', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0, null=True)),
                ('total_price', models.FloatField(default=0, null=True)),
                ('order_filter', models.IntegerField(default=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item')),
            ],
        ),
        migrations.CreateModel(
            name='Item_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.category')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_count', models.IntegerField()),
                ('drow_status', models.IntegerField(default=0)),
                ('scan_url', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('order_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.hotel_order_master')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.owner')),
            ],
        ),
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lucky_drow', models.CharField(default=0, max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.bill')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.customer')),
            ],
        ),
        migrations.CreateModel(
            name='luckydrow_winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_participant', models.IntegerField()),
                ('youtube_url', embed_video.fields.EmbedVideoField()),
                ('date', models.DateField(auto_now_add=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('winner_participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.participant')),
            ],
        ),
        migrations.AddField(
            model_name='hotel_order_master',
            name='table',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='owner.table'),
        ),
        migrations.CreateModel(
            name='Hotel_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField(default=0)),
                ('qty', models.IntegerField()),
                ('cook_status', models.CharField(default='Pendding', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.table')),
            ],
        ),
    ]
