# Generated by Django 5.1.3 on 2024-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='', max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(unique=True)),
                ('pin', models.IntegerField()),
                ('hotel_address', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
