# Generated by Django 5.1.3 on 2025-02-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_order_master',
            name='cash_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hotel_order_master',
            name='phone_pe_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hotel_order_master',
            name='pos_machine_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
