# Generated by Django 5.1.3 on 2025-02-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gst_status',
            field=models.IntegerField(default=1),
        ),
    ]
