# Generated by Django 5.1.3 on 2024-11-28 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0002_item_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                ("person_count", models.IntegerField()),
                ("drow_status", models.IntegerField(default=0)),
                ("scan_url", models.CharField(max_length=100)),
                ("status", models.IntegerField(default=1)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="owner.owner",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Item_category",
        ),
    ]
