# Generated by Django 5.1.3 on 2025-02-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_hotel_order_master_cash_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_order_master',
            name='paid_status',
            field=models.IntegerField(default=0),
        ),
    ]
