# Generated by Django 5.1.3 on 2024-12-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0003_bill_delete_item_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
    ]
