# Generated by Django 5.1.3 on 2025-02-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_hotel_order_master_paid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_order_master',
            name='paid_status',
        ),
    ]
