# Generated by Django 5.1.3 on 2024-12-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0004_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lucky_drow", models.CharField(default=0, max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("status", models.IntegerField(default=1)),
                (
                    "bill",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="owner.bill",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="owner.customer",
                    ),
                ),
            ],
        ),
    ]
