# Generated by Django 5.1.3 on 2025-02-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_remove_hotel_order_master_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_order_master',
            name='discount_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hotel_order_master',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
