# Generated by Django 5.1.3 on 2024-12-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.bill')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.participant')),
            ],
        ),
    ]
