# Generated by Django 5.1.3 on 2024-12-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_luckydrow_winner_delete_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luckydrow_winner',
            name='participant',
        ),
        migrations.AddField(
            model_name='luckydrow_winner',
            name='winner_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.participant'),
        ),
    ]
