# Generated by Django 5.1.3 on 2024-12-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_remove_luckydrow_winner_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydrow_winner',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
