# Generated by Django 5.1.3 on 2024-12-18 11:04

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_luckydrow_winner_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydrow_winner',
            name='youtube_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
