# Generated by Django 5.1.3 on 2024-12-27 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField(default=0)),
                ('qty', models.IntegerField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.table')),
            ],
        ),
    ]
