# Generated by Django 5.1.3 on 2024-12-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0016_new_hotel_cart_orderdetail_ordermaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='ordered_date',
        ),
        migrations.DeleteModel(
            name='new_Hotel_cart',
        ),
    ]
