# Generated by Django 5.1.3 on 2024-12-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0017_remove_orderdetail_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderMaster',
            new_name='Hotel_order_Master',
        ),
        migrations.CreateModel(
            name='Hotel_order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(default=True)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0, null=True)),
                ('total_price', models.FloatField(default=0, null=True)),
                ('order_filter', models.IntegerField(default=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
