# Generated by Django 5.1.3 on 2024-12-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0018_rename_ordermaster_hotel_order_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_order_detail',
            name='table_number',
        ),
    ]
