# Generated by Django 5.1.3 on 2024-12-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0019_remove_hotel_order_detail_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_cart',
            name='cook_status',
            field=models.IntegerField(default=0),
        ),
    ]
