# Generated by Django 5.1.3 on 2024-12-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0020_hotel_cart_cook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_cart',
            name='cook_status',
            field=models.CharField(default='Pendding', max_length=100),
        ),
    ]
