# Generated by Django 5.1.3 on 2024-12-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0021_alter_hotel_cart_cook_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='name',
        ),
        migrations.AddField(
            model_name='bill',
            name='order_Master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.hotel_order_master'),
        ),
    ]
