# Generated by Django 5.1.3 on 2024-12-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0022_remove_bill_amount_remove_bill_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='order_Master',
            new_name='order_master',
        ),
    ]
