# Generated by Django 5.1.3 on 2024-12-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tea_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(unique=True)),
                ('pin', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
