# Generated by Django 5.1.3 on 2024-12-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
