# Generated by Django 5.1.3 on 2024-12-25 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0003_tea_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tea.tea_employee')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tea.tea_item')),
            ],
        ),
        migrations.DeleteModel(
            name='Tea_table',
        ),
    ]
