# Generated by Django 5.1.3 on 2024-12-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0004_cart_delete_tea_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
