# Generated by Django 5.1.3 on 2024-12-25 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0006_ordermaster_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='dish_marathi_name',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='table_number',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tea.tea_employee'),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tea.tea_employee'),
        ),
    ]
