# Generated by Django 5.1.3 on 2024-12-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0007_remove_orderdetail_dish_marathi_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='', max_length=100)),
                ('contact_number', models.IntegerField(unique=True)),
                ('hotel_address', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
