# Generated by Django 5.1.3 on 2025-01-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0008_tea_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order_by', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
