# Generated by Django 5.1.3 on 2025-01-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0009_tea_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select_category_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tea.tea_category')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tea.tea_item')),
            ],
        ),
    ]
